ENVIRONMENT:
  TYPE: "mp3d"
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  ADDITION_ACTION: ['PAUSE']
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR','RGB_BACK_SENSOR','RGB_LEFT_SENSOR','RGB_RIGHT_SENSOR','RGB_FORWARD_SENSOR','RGB_SENSOR_30','RGB_SENSOR_60','RGB_SENSOR_90','RGB_SENSOR_120','RGB_SENSOR_150','RGB_SENSOR_180','RGB_SENSOR_210','RGB_SENSOR_240','RGB_SENSOR_270','RGB_SENSOR_300','RGB_SENSOR_330', 'DEPTH_SENSOR_30','DEPTH_SENSOR_60','DEPTH_SENSOR_90','DEPTH_SENSOR_120','DEPTH_SENSOR_150','DEPTH_SENSOR_180','DEPTH_SENSOR_210','DEPTH_SENSOR_240','DEPTH_SENSOR_270','DEPTH_SENSOR_300','DEPTH_SENSOR_330']
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    POSITION: [0, 0.5, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 30
    POSITION: [0, 0.5, 0]

  RGB_BACK_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    ORIENTATION: [0.0, 3.141592653589793, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_back
  RGB_LEFT_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    ORIENTATION: [0.0, 1.5707963267948966, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_left
  RGB_RIGHT_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    ORIENTATION: [0.0, 4.71238898038469, 0.0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_right
  RGB_FORWARD_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    ORIENTATION: [0.0, 0.0, 0.0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_forward
  RGB_SENSOR_30:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 0.5235987755982988, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_30.0
  RGB_SENSOR_60:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 1.0471975511965976, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_60.0
  RGB_SENSOR_90:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 1.5707963267948966, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_90.0
  RGB_SENSOR_120:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 2.0943951023931953, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_120.0
  RGB_SENSOR_150:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 2.6179938779914944, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_150.0
  RGB_SENSOR_180:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 3.141592653589793, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_180.0
  RGB_SENSOR_210:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 3.6651914291880923, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_210.0
  RGB_SENSOR_240:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 4.1887902047863905, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_240.0
  RGB_SENSOR_270:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 4.71238898038469, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_270.0
  RGB_SENSOR_300:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 5.235987755982989, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_300.0
  RGB_SENSOR_330:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 30
    ORIENTATION: [0.0, 5.759586531581287, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimRGBSensor
    UUID: rgb_330.0


  DEPTH_SENSOR_30:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 30
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    ORIENTATION: [0.0, 0.5235987755982988, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_30.0
  DEPTH_SENSOR_60:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 1.0471975511965976, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_60.0
  DEPTH_SENSOR_90:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 1.5707963267948966, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimDepthSensor
    NORMALIZE_DEPTH: True
    UUID: depth_90.0
  DEPTH_SENSOR_120:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 2.0943951023931953, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    TYPE: HabitatSimDepthSensor
    NORMALIZE_DEPTH: True
    UUID: depth_120.0
  DEPTH_SENSOR_150:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 2.6179938779914944, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_150.0
  DEPTH_SENSOR_180:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 3.141592653589793, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_180.0
  DEPTH_SENSOR_210:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 3.6651914291880923, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_210.0
  DEPTH_SENSOR_240:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 4.1887902047863905, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_240.0
  DEPTH_SENSOR_270:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 4.71238898038469, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_270.0
  DEPTH_SENSOR_300:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 5.235987755982989, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_300.0
  DEPTH_SENSOR_330:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    HFOV: 30
    ORIENTATION: [0.0, 5.759586531581287, 0.0]
    POSITION: [0, 0.5, 0]
    SENSOR_SUBTYPE: PINHOLE
    NORMALIZE_DEPTH: True
    TYPE: HabitatSimDepthSensor
    UUID: depth_330.0
TASK:
  # possible_actions: ['stop', 'move_forward', 'turn_left', 'turn_right', 'TurnRight90', 'TurnLeftt90', 'PAUSE']
  # success_measure: "success"
  # reward_measure: "distance_to_goal"
  TYPE: VLN-v0
  SENSORS: ['PANORAMIC_PERCEPTION_SENSOR','INSTRUCTION_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  SUCCESS_DISTANCE: 3.0
DATASET:
  TYPE: R2RVLN-v2
  SPLIT: val_unseen
  DATA_PATH: "data/datasets/vln/mp3d/r2r/v2/{split}/{split}.json.gz"
  SCENE_DIR: "data/scene_datasets/"
  EPI_NUM: 2
